---
- name: Gather Facts Example
  hosts: webservers
  tasks:
    - name: Print out the OS family
      debug:
        msg: "The OS family is {{ ansible_os_family }}"


        ansible-playbook gather-facts-example.yml -i inventory