---
- name: Apache installation for ubuntuservers
  hosts: ubuntuservers
  become: true
  tasks:
   - name: installing apache
     apt:
       name: apache2
       state: latest

   - name: index.html
     copy:
       content: "<h1>Hello Ansible</h1>"
       dest: /var/www/html/index.html

   - name: restart apache2
     service:
       name: apache2
       state: restarted
       enabled: yes

- name: Apache wget installation for webservers
  hosts: webservers
  become: true
  tasks:
    - name: installing httpd and wget
      yum:
        pkg: ['httpd', 'wget']
        state: present